### ISSUE TITLE
UniswapError: chainId can not be found on the provider

### ISSUE THREAD

**Issue by JanOwiesniak** [Anish-Agnihotri/pool-sniper#2]
**node version**
v14.18.0

**npm version**
v6.14.15

**issue**
running `npm run-script dev` results in

```
UniswapError: chainId can not be found on the provider
...
at Sniper.<anonymous> (pool-sniper/src/sniper.ts:88:43)
```

**Comment by Anish-Agnihotri** [comment]
Closing kudos to @joshstevens19's help on native support for Polygon!

@MohitKumar1991 the approach did work—please feel free to use the code in any way.
